version: "3.9"

services:
  ####################################
  ###         Applications         ###
  ####################################
  postgres-db:
    image: postgres:14.1-alpine3.15
    restart: always
    environment:
      POSTGRES_PASSWORD: localone
      POSTGRES_USER: user
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - serverside-network
    ports:
      - "27017:27017"

  mongo-express-server:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017
    networks:
      - serverside-network

networks:
  serverside-network:
    driver: bridge